# Generated by Django 3.1.3 on 2020-11-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(verbose_name='The original ATMT website url')),
                ('facebook', models.URLField(verbose_name='The ATMT Facebook Page url')),
                ('twitter', models.URLField(verbose_name='The ATMT Twitter handle url')),
                ('instagram', models.URLField(verbose_name='The ATMT Instgram Account url')),
                ('facebook_check', models.BooleanField(default=True, verbose_name='Facebook')),
                ('twitter_check', models.BooleanField(default=True, verbose_name='Twitter')),
                ('instagram_check', models.BooleanField(default=True, verbose_name='Instagram')),
                ('address', models.TextField(verbose_name='The Address of ATMT office')),
                ('aboutfooter', models.CharField(help_text='This should not exceed more than 150 characters', max_length=150, verbose_name='About the ATMT for the footer')),
                ('aboutright', models.TextField(verbose_name='About ATMT in the left side of about us section')),
                ('aboutleft', models.TextField(verbose_name='About ATMT in the right side of about us section')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
