# Generated by Django 3.1.3 on 2020-11-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='aboutleft',
            field=models.TextField(verbose_name='About ATMT in the left side of about us section'),
        ),
        migrations.AlterField(
            model_name='description',
            name='aboutright',
            field=models.TextField(verbose_name='About ATMT in the right side of about us section'),
        ),
    ]
