# Generated by Django 3.1.3 on 2020-11-13 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='The Date and Time when the event will go live')),
                ('streamingvideoheader', models.CharField(max_length=600, verbose_name='Live Streaming Video Header')),
                ('live', models.BooleanField(default=True, help_text='Check this only if the video is live', verbose_name='Live Video')),
                ('streamingvideolink', models.URLField(blank=True, null=True, verbose_name='Live Video Link')),
                ('videoid', models.CharField(blank=True, max_length=500, null=True, verbose_name='Facebook/YouTube Video ID')),
                ('usernamefb', models.CharField(blank=True, max_length=500, null=True, verbose_name='Facebook User ID')),
                ('embeedlink', models.URLField(blank=True, null=True, verbose_name='Embeed Link of Posts or Video')),
                ('streamingvideodescription_left', models.TextField(verbose_name='Streaming Video Short Description Left')),
                ('streamingvideodescription_right', models.TextField(verbose_name='Streaming Video Short Description Right')),
            ],
            options={
                'verbose_name_plural': 'Live Videos',
            },
        ),
    ]
